# Generated by Django 5.1.6 on 2026-05-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coordinatorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbudget',
            name='food',
        ),
        migrations.RemoveField(
            model_name='eventbudget',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='eventbudget',
            name='other',
        ),
        migrations.RemoveField(
            model_name='eventbudget',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='eventbudget',
            name='venue',
        ),
    ]
