# Generated by Django 5.1.6 on 2026-05-16 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_eventbudget_food_remove_eventbudget_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
