# Generated by Django 5.1.6 on 2026-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_expenselog_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselog',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
