# Generated by Django 5.1.6 on 2026-05-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='other_volunteer_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_role',
            field=models.CharField(blank=True, choices=[('fundraising', 'Fundraising Support'), ('door_to_door', 'Door-to-door Campaign'), ('mobilising_voters', 'Mobilising Voters'), ('social_media', 'Social Media Support'), ('recruiting', 'Recruiting Volunteers'), ('materials', 'Distributing Campaign Materials'), ('data_collection', 'Data Collection'), ('community_listening', 'Community Listening'), ('barazas', 'Holding Barazas & Household Meetings'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinators', to='accounts.constituency'),
        ),
    ]
