# Generated by Django 5.1.6 on 2026-05-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
