# Generated by Django 5.1.6 on 2026-05-24 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_gallery_title_remove_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='managed_constituency',
        ),
        migrations.AlterField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='accounts.county'),
        ),
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='accounts.constituency'),
        ),
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='accounts.ward'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='accounts.constituency'),
        ),
        migrations.AlterUniqueTogether(
            name='constituency',
            unique_together={('county', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pollingstation',
            unique_together={('ward', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('constituency', 'name')},
        ),
    ]
